/**
 * ユーザーデータコンテキスト
 * ログイン中のユーザーのゲームデータを管理
 */

import { createContext, useContext, useEffect, useState, ReactNode, useCallback, useRef } from 'react';
import { useAuth } from './AuthContext';
import { userService } from '../services/user';
import { habitService } from '../services/habit';
import { achievementService } from '../services/achievement';
import { seedService } from '../services/seed';
import { toast } from 'sonner';
import { playSoundGlobal } from '../hooks/useSound';
import type { User, Habit, HabitRecord, Achievement, UserAchievement, Job, UserJob, Gender } from '../types';

interface UserContextType {
  // ユーザーデータ
  userData: User | null;
  habits: Habit[];
  habitRecords: Map<string, HabitRecord[]>;
  achievements: Achievement[];
  userAchievements: UserAchievement[];
  jobs: Job[];
  userJobs: UserJob[];
  
  // ローディング状態
  isLoading: boolean;
  
  // プロフィール設定が必要かどうか
  needsProfileSetup: boolean;
  
  // データ操作関数
  refreshUserData: () => Promise<void>;
  refreshHabits: () => Promise<void>;
  createHabit: (habit: Partial<Habit>) => Promise<Habit | null>;
  updateHabit: (habitId: string, updates: Partial<Habit>) => Promise<Habit | null>;
  deleteHabit: (habitId: string) => Promise<boolean>;
  completeHabit: (habitId: string, date?: string, note?: string) => Promise<HabitRecord | null>;
  getHabitRecordsForDate: (habitId: string, date: string) => HabitRecord | undefined;
  isHabitCompletedToday: (habitId: string) => boolean;
  // 職業選択
  selectJob: (jobId: string) => Promise<boolean>;
  // 性別変更
  changeGender: (gender: Gender) => Promise<boolean>;
}

const UserContext = createContext<UserContextType | undefined>(undefined);

export function UserProvider({ children }: { children: ReactNode }) {
  const { user, isAuthenticated } = useAuth();
  
  const [userData, setUserData] = useState<User | null>(null);
  const [habits, setHabits] = useState<Habit[]>([]);
  const [habitRecords, setHabitRecords] = useState<Map<string, HabitRecord[]>>(new Map());
  const [achievements, setAchievements] = useState<Achievement[]>([]);
  const [userAchievements, setUserAchievements] = useState<UserAchievement[]>([]);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [userJobs, setUserJobs] = useState<UserJob[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [needsProfileSetup, setNeedsProfileSetup] = useState(false);

  // 今日の日付をYYYY-MM-DD形式で取得（ユーザーのタイムゾーンを考慮）
  const getTodayDate = useCallback(() => {
    const timezone = userData?.timezone ?? 'Asia/Tokyo';
    try {
      const now = new Date();
      const formatter = new Intl.DateTimeFormat('sv-SE', {
        timeZone: timezone,
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
      });
      return formatter.format(now);
    } catch {
      // タイムゾーンが無効な場合はローカル時刻を使用
      return new Date().toISOString().split('T')[0];
    }
  }, [userData?.timezone]);

  // ユーザーデータを取得または作成
  const refreshUserData = useCallback(async () => {
    if (!user) {
      setUserData(null);
      setNeedsProfileSetup(false);
      return;
    }

    try {
      const userId = user.userId;
      const existingUser = await userService.getUser(userId);

      // ユーザーが存在しない場合、またはdisplayNameが自動生成されたままの場合はプロフィール設定が必要
      if (!existingUser) {
        setUserData(null);
        setNeedsProfileSetup(true);
        return;
      }

      // displayNameがメールアドレスの@より前の部分と同じ場合は、自動生成されたとみなしてプロフィール設定を促す
      // ただし、SSO以外の通常サインアップの場合は除外
      const email = existingUser.email || '';
      const defaultDisplayName = email.split('@')[0];
      const isAutoGenerated = existingUser.displayName === defaultDisplayName && 
                              !existingUser.displayName.includes(' ');
      
      // Google SSOの場合のみプロフィール設定を促す（ユーザーが明示的にdisplayNameを設定していない場合）
      // ただし、ユーザーが既に習慣を作成している場合はスキップ
      setUserData(existingUser);
      setNeedsProfileSetup(false);
    } catch (error) {
      console.error('Failed to fetch/create user data:', error);
      setNeedsProfileSetup(false);
    }
  }, [user]);

  // 習慣データを取得
  const refreshHabits = useCallback(async () => {
    if (!user) {
      setHabits([]);
      return;
    }

    try {
      const userId = user.userId;
      const userHabits = await habitService.getHabits(userId);
      setHabits(userHabits.filter(h => !h.isArchived && h.isActive));

      // 各習慣の記録を並列で取得（大幅な高速化）
      const recordPromises = userHabits.map(async habit => {
        const records = await habitService.getHabitRecords(habit.habitId);
        return { habitId: habit.habitId, records };
      });
      const results = await Promise.all(recordPromises);
      const recordsMap = new Map<string, HabitRecord[]>();
      for (const { habitId, records } of results) {
        recordsMap.set(habitId, records);
      }
      setHabitRecords(recordsMap);
    } catch (error) {
      console.error('Failed to fetch habits:', error);
    }
  }, [user]);

  // アチーブメントとジョブを取得
  const refreshAchievementsAndJobs = useCallback(async () => {
    if (!user) {
      setAchievements([]);
      setUserAchievements([]);
      setJobs([]);
      setUserJobs([]);
      return;
    }

    try {
      const userId = user.userId;
      
      // シード済みチェック（LocalStorageフラグ）
      const seedCompleted = seedService.isSeedCompleted();
      
      if (!seedCompleted) {
        // まずマスターデータの存在を素早くチェック
        const { hasAchievements, hasJobs } = await seedService.checkMasterDataExists();
        
        if (!hasAchievements || !hasJobs) {
          await seedService.seedAll();
        }
        
        // シード完了をマーク
        seedService.markSeedCompleted();
      }
      
      // 並行してデータを取得
      const [allAchievements, userAch, allJobs, userJ] = await Promise.all([
        userService.getAchievements(),
        userService.getUserAchievements(userId),
        userService.getJobs(),
        userService.getUserJobs(userId),
      ]);

      setAchievements(allAchievements);
      setUserAchievements(userAch);
      setJobs(allJobs);
      setUserJobs(userJ);
    } catch (error) {
      console.error('Failed to fetch achievements/jobs:', error);
    }
  }, [user]);

  // 初回ロード（並列化で高速化）
  useEffect(() => {
    const loadData = async () => {
      if (isAuthenticated && user) {
        setIsLoading(true);
        try {
          // すべてのデータを並列で取得（大幅な高速化）
          await Promise.all([
            refreshUserData(),
            refreshHabits(),
            refreshAchievementsAndJobs(),
          ]);
        } catch (error) {
          console.error('❌ Failed to load initial data:', error);
        } finally {
          setIsLoading(false);
        }
      } else {
        setUserData(null);
        setHabits([]);
        setHabitRecords(new Map());
        setAchievements([]);
        setUserAchievements([]);
        setJobs([]);
        setUserJobs([]);
        setIsLoading(false);
      }
    };
    
    loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isAuthenticated, user?.userId]);

  // 習慣を作成
  const createHabit = async (habit: Partial<Habit>): Promise<Habit | null> => {
    if (!user) return null;

    const newHabit = await habitService.createHabit({
      ...habit,
      userId: user.userId,
    });

    if (newHabit) {
      setHabits(prev => [...prev, newHabit]);
    }

    return newHabit;
  };

  // 習慣を更新
  const updateHabit = async (habitId: string, updates: Partial<Habit>): Promise<Habit | null> => {
    const updatedHabit = await habitService.updateHabit(habitId, updates);

    if (updatedHabit) {
      setHabits(prev => prev.map(h => h.habitId === habitId ? updatedHabit : h));
    }

    return updatedHabit;
  };

  // 習慣を削除
  const deleteHabit = async (habitId: string): Promise<boolean> => {
    const success = await habitService.deleteHabit(habitId);

    if (success) {
      setHabits(prev => prev.filter(h => h.habitId !== habitId));
      // 記録も削除（表示から除外）
      setHabitRecords(prev => {
        const newMap = new Map(prev);
        newMap.delete(habitId);
        return newMap;
      });
    }

    return success;
  };

  // 習慣を完了
  const completeHabit = async (
    habitId: string,
    date?: string,
    note?: string
  ): Promise<HabitRecord | null> => {
    if (!user) return null;

    const completedDate = date ?? getTodayDate();
    const oldLevel = userData?.level ?? 1;
    
    const result = await habitService.recordCompletion(
      habitId,
      user.userId,
      completedDate,
      note
    );

    if (result.record) {
      // ローカルステートを即座に更新（UIレスポンス向上）
      setHabitRecords(prev => {
        const newMap = new Map(prev);
        const existing = newMap.get(habitId) ?? [];
        newMap.set(habitId, [...existing, result.record!]);
        return newMap;
      });

      // 習慣のストリーク更新をローカルで即座に反映
      // 注: 実際のストリーク値はrecordCompletionで計算されるため、
      // バックグラウンド更新で正確な値に更新される
      setHabits(prev => prev.map(h => {
        if (h.habitId === habitId) {
          // ストリーク値はresult.record.streakAtCompletionから取得
          const newStreak = result.record!.streakAtCompletion;
          return {
            ...h,
            currentStreak: newStreak,
            bestStreak: Math.max(h.bestStreak, newStreak),
            totalCompletions: h.totalCompletions + 1,
          };
        }
        return h;
      }));

      // ユーザーデータと称号チェックを並列で実行（バックグラウンド更新）
      const updatePromise = (async () => {
        const [updatedUser, updatedHabits] = await Promise.all([
          userService.getUser(user.userId),
          habitService.getHabits(user.userId),
        ]);
        
        if (updatedUser) {
          setUserData(updatedUser);
          setHabits(updatedHabits.filter(h => !h.isArchived && h.isActive));
          
          // レベルアップ通知
          if (updatedUser.level > oldLevel) {
            playSoundGlobal('levelUp');
            toast.success(`🎉 レベルアップ！ Lv.${updatedUser.level} になりました！`, {
              duration: 4000,
              style: {
                background: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
                border: '2px solid #fbbf24',
                color: '#fbbf24',
              },
            });
          }
          
          // アチーブメントチェック（称号獲得）
          if (achievements.length > 0) {
            const checkResult = await achievementService.checkAchievements(
              updatedUser,
              updatedHabits,
              achievements,
              userAchievements
            );

            // 新しく解除されたアチーブメントがあれば通知
            if (checkResult.newlyUnlocked.length > 0) {
              playSoundGlobal('achievement');
              for (const ach of checkResult.newlyUnlocked) {
                toast.success(`🏆 称号かいほう「${ach.name}」！ +${ach.expReward} EXP`, {
                  duration: 5000,
                  style: {
                    background: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
                    border: '2px solid #a855f7',
                    color: '#e9d5ff',
                  },
                });
              }
              // UserAchievementsを再取得
              const updatedUserAch = await userService.getUserAchievements(user.userId);
              setUserAchievements(updatedUserAch);
              // 経験値も更新されたので再取得
              const finalUser = await userService.getUser(user.userId);
              if (finalUser) setUserData(finalUser);
            }
          }

          // ジョブ解放チェック
          if (jobs.length > 0) {
            const jobCheckResult = await achievementService.checkJobs(
              updatedUser,
              jobs,
              userJobs,
              userAchievements
            );

            // 新しく解放されたジョブがあれば通知
            if (jobCheckResult.newlyUnlocked.length > 0) {
              playSoundGlobal('jobUnlock');
              for (const job of jobCheckResult.newlyUnlocked) {
                toast.success(`⚔️ しょくぎょう「${job.name}」がかいほうされた！`, {
                  duration: 5000,
                  style: {
                    background: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
                    border: '2px solid #7c3aed',
                    color: '#c4b5fd',
                  },
                });
              }
              // UserJobsを再取得
              const updatedUserJobs = await userService.getUserJobs(user.userId);
              setUserJobs(updatedUserJobs);
            }
          }
        }
      })();

      // バックグラウンドで更新を待つ（UIはブロックしない）
      updatePromise.catch(err => console.error('Background update failed:', err));
    }

    return result.record;
  };

  // 特定の日の記録を取得
  const getHabitRecordsForDate = (habitId: string, date: string): HabitRecord | undefined => {
    const records = habitRecords.get(habitId) ?? [];
    return records.find(r => r.completedDate === date && r.completed);
  };

  // 今日完了済みかどうか
  const isHabitCompletedToday = (habitId: string): boolean => {
    const today = getTodayDate();
    return !!getHabitRecordsForDate(habitId, today);
  };

  // 職業を選択（解放済みの職業のみ選択可能）
  const selectJob = async (jobId: string): Promise<boolean> => {
    if (!user || !userData) return false;

    // beginner（みならい）は常に選択可能
    const isUnlocked = jobId === 'beginner' || userJobs.some(uj => uj.jobId === jobId && uj.isUnlocked);
    if (!isUnlocked) {
      console.log('❌ この職業はまだ解放されていません');
      return false;
    }

    try {
      const updatedUser = await userService.updateUser(user.userId, { currentJobId: jobId });
      console.log('⚔️ selectJob - updatedUser:', updatedUser);
      console.log('⚔️ selectJob - updatedUser.currentJobId:', updatedUser?.currentJobId);
      if (updatedUser) {
        // 明示的にcurrentJobIdを含む新しいオブジェクトを作成
        const newUserData = { ...userData, ...updatedUser, currentJobId: jobId };
        console.log('⚔️ selectJob - newUserData:', newUserData);
        setUserData(newUserData);
        const job = jobs.find(j => j.jobId === jobId);
        console.log(`⚔️ 職業を「${job?.name ?? jobId}」に変更しました！`);
        return true;
      }
      return false;
    } catch (error) {
      console.error('Failed to select job:', error);
      return false;
    }
  };

  // 性別を変更
  const changeGender = async (gender: Gender): Promise<boolean> => {
    if (!user || !userData) return false;

    try {
      const updatedUser = await userService.updateUser(user.userId, { gender });
      console.log('👤 changeGender - updatedUser:', updatedUser);
      console.log('👤 changeGender - updatedUser.gender:', updatedUser?.gender);
      if (updatedUser) {
        // 明示的にgenderを含む新しいオブジェクトを作成
        const newUserData = { ...userData, ...updatedUser, gender };
        console.log('👤 changeGender - newUserData:', newUserData);
        setUserData(newUserData);
        const genderLabel = gender === 'male' ? '男性' : '女性';
        console.log(`👤 性別を「${genderLabel}」に変更しました！`);
        return true;
      }
      return false;
    } catch (error) {
      console.error('Failed to change gender:', error);
      return false;
    }
  };

  return (
    <UserContext.Provider
      value={{
        userData,
        habits,
        habitRecords,
        achievements,
        userAchievements,
        jobs,
        userJobs,
        isLoading,
        needsProfileSetup,
        refreshUserData,
        refreshHabits,
        createHabit,
        updateHabit,
        deleteHabit,
        completeHabit,
        getHabitRecordsForDate,
        isHabitCompletedToday,
        selectJob,
        changeGender,
      }}
    >
      {children}
    </UserContext.Provider>
  );
}

export function useUser() {
  const context = useContext(UserContext);
  if (context === undefined) {
    throw new Error('useUser must be used within a UserProvider');
  }
  return context;
}
